### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jlboba** [qusaifares/footwiz#1]
# Feedback 

Overall result: Complete! 

## Code Quality 

Overall good organization of components and files, as well as clean, easy to read and understand code. Good handling of data in the top-most component that needs it to avoid multiple API calls. Really nice work!

## Technical Requirements 

Met all of them! Renders in browser with no errors, deployed to heroku, used the technologies required. 

## Creativity and Interface 

Really beautiful UI! It's not easy to display that much data in such a nice way, super impressive and professional-looking without getting in the way of the functionality. It's easy to read and for the user to understand, gives nice feedback on hover and etc. Just really wonderful job overall!

## Functionality 

Works perfectly as intended, on both browser and mobile versions!

## Presentation 

Great README! Really easy to read and understand without being too dense. Covers all the basic necessities, and love the screen recorded gif of the app functionality as well.

Really wonderful job overall 😄  

( p.s. feel free to close the issue once you've read it! )

**Comment by qusaifares** [comment]
Thanks for the feedback!
